package main

var componentMetricMap = map[string][]string{
	"TiDB": {
		"TiDB_CPU",
		"TiDB_CPU_Delta",
		"QPS",
		"TPS",
		"Duration_P80",
		"Duration_P999",
		"Connection Idel Duration_80_in_txn",
		"Connection Idel Duration_80_not_in_txn",
		"Avg_Latency",
		"Max_Latency",
		"Parse",
		"Compile",
		"Execute",
		"TSO",
		"Get",
		"PessimisticLock",
		"TiDB_Coprocessor",
		"Prewrite",
		"Commit",
		"Plan_Cache_Ops",
	},
	"TiKV": {
		"TiKV_CPU",
		"TiKV_CPU_Delta",
		"TiKV_Coprocessor",
		"KV_Prewrite",
		"KV_Get",
		"KV_Pessimistic_lock",
		"Apply Log",
		"Append Log",
		"Commit Log",
	},
}

var metrics = map[string]string{
	"TiDB_CPU":                               "avg_over_time(avg(rate(process_cpu_seconds_total{job=\"tidb\"}[1m]))[%ds:])",
	"TiDB_CPU_Delta":                         "avg_over_time((max(rate(process_cpu_seconds_total{job=\"tidb\"}[1m])) - min(rate(process_cpu_seconds_total{job=\"tidb\"}[1m])))[%ds:])",
	"QPS":                                    "avg_over_time(sum(rate(tidb_server_query_total[1m])) [%ds:])",
	"TPS":                                    "avg_over_time(sum(rate(tidb_session_transaction_duration_seconds_count[1m])) [%ds:])",
	"Duration_P80":                           "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))[%ds:])",
	"Duration_P999":                          "1000*avg_over_time(histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))[%ds:])",
	"Connection Idel Duration_80_in_txn":     "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_server_conn_idle_duration_seconds_bucket{in_txn='1'}[1m])) by (le))[%ds:])",
	"Connection Idel Duration_80_not_in_txn": "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_server_conn_idle_duration_seconds_bucket{in_txn='0'}[1m])) by (le))[%ds:])",
	"Avg_Latency":                            "1000*avg_over_time((sum(rate(tidb_server_handle_query_duration_seconds_sum{sql_type!=\"internal\"}[1m])) / sum(rate(tidb_server_handle_query_duration_seconds_count{sql_type!=\"internal\"}[1m])))[%ds:])",
	"Max_Latency":                            "1000*max_over_time(histogram_quantile(1, sum(rate(tidb_server_handle_query_duration_seconds_bucket[1m])) by (le))[%ds:])",
	"Parse":                                  "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_session_parse_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le, sql_type))[%ds:])",
	"Compile":                                "1000*avg_over_time(histogram_quantile(0.99, sum(rate(tidb_session_compile_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))[%ds:])",
	"Execute":                                "1000*avg_over_time(histogram_quantile(0.99, sum(rate(tidb_session_execute_duration_seconds_bucket{sql_type=\"general\"}[1m])) by (le))[%ds:])",
	"TSO":                                    "1000*avg_over_time(histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{type=\"wait\"}[1m])) by (le))[%ds:])",
	"Get":                                    "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_tikvclient_request_seconds_bucket{type=\"Get\"}[1m])) by (le))[%ds:])",
	"PessimisticLock":                        "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_tikvclient_request_seconds_bucket{type=\"PessimisticLock\"}[1m])) by (le))[%ds:])",
	"TiDB_Coprocessor":                       "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_tikvclient_request_seconds_bucket{type=\"Cop\"}[1m])) by (le))[%ds:])",
	"Prewrite":                               "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_tikvclient_request_seconds_bucket{type=\"Prewrite\"}[1m])) by (le))[%ds:])",
	"Commit":                                 "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tidb_tikvclient_request_seconds_bucket{type=\"Commit\"}[1m])) by (le))[%ds:])",
	"Plan_Cache_Ops":                         "avg_over_time(sum(rate(tidb_server_plan_cache_total[1m]))[%ds:])",
	"TiKV_CPU":                               "avg_over_time(avg(rate(process_cpu_seconds_total{job=~\".*tikv\"}[1m]))[%ds:])",
	"TiKV_CPU_Delta":                         "avg_over_time((max(rate(process_cpu_seconds_total{job=~\".*tikv\"}[1m])) - min(rate(process_cpu_seconds_total{job=~\".*tikv\"}[1m])))[%ds:])",
	"TiKV_Coprocessor":                       "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tikv_grpc_msg_duration_seconds_bucket{type=\"coprocessor\"}[1m])) by (le))[%ds:])",
	"KV_Prewrite":                            "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tikv_grpc_msg_duration_seconds_bucket{type=\"kv_prewrite\"}[1m])) by (le))[%ds:])",
	"KV_Get":                                 "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tikv_grpc_msg_duration_seconds_bucket{type=\"kv_get\"}[1m])) by (le))[%ds:])",
	"KV_Pessimistic_lock":                    "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tikv_grpc_msg_duration_seconds_bucket{type=\"kv_prewrite\"}[1m])) by (le))[%ds:])",
	"Apply Log":                              "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tikv_raftstore_apply_log_duration_seconds_bucket[1m])) by (le))[%ds:])",
	"Append Log":                             "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tikv_raftstore_append_log_duration_seconds_bucket[1m])) by (le))[%ds:])",
	"Commit Log":                             "1000*avg_over_time(histogram_quantile(0.80, sum(rate(tikv_raftstore_commit_log_duration_seconds_bucket[1m])) by (le))[%ds:])",
}
